### PR TITLE
Grab kafka from the env for the ERS DB writer

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Comment by plasorak** [comment]
fixes https://github.com/DUNE-DAQ/microservices/issues/34

**Comment by jcpunk** [comment]
Can this be merged?

**Comment by plasorak** [comment]
I can't remember... I think pocket has to (had to?) be modified too.

**Comment by jcpunk** [comment]
I'm showing https://github.com/jcpunk/pocket/commit/b445a133ed48b8aaa44e39ed6093bace540ca415#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R99 which looks like it has the right bits in place.

I'm tempted to also make the kafka topic an env var with a default of `erskafka-reporting` that might make it easier to deploy test instances... thoughts?

**Comment by mroda88** [comment]
Guys, this is not relevant anymore, plus it's going to be replaced soon anyway. SO I'm closing this.

**Pull request closed without merging**
