### PR TITLE
Self documentation HTML for the root of the run services.

### LINKED ISSUE #82: Better description of the service than "best things since sliced bread"
The root of the run registry and run number microservices should output something more explanatory than "best thing since sliced bread". I'd suggest something like:
```
$ curl runnumber.url/
Run number microservices vX.X.X
Accepted routes:
/runnumber/get
/runnumber/getNew
```
And similarly for the run registry.

### PR DESCRIPTION
**Pull request by plasorak**
Fixes https://github.com/DUNE-DAQ/microservices/issues/82

Root now return some digestible html.

### CODE REVIEW

**Comment by jcpunk** [comment]
I very much like the improved index page!

**Comment by plasorak** [comment]
Anybody wants to test this? Pat/Tiago?

**Comment by TiagoTAlves** [comment]
I'll test this

**Comment by jcpunk** [comment]
I don't really know anything about this service, so I'm a bit worried about being on the maintainers list...

**Comment by plasorak** [comment]
OK I can remove you

**Review by TiagoTAlves — APPROVED** [review]
Tested it by merging with my runservices branch and we get a working html webpage as expected

**Pull request merged**
